2021-05-04 13:35:17,544 INFO    MainThread:58 [wandb_setup.py:_flush():69] setting env: {}
2021-05-04 13:35:17,544 INFO    MainThread:58 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-04 13:35:17,545 INFO    MainThread:58 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8d3153ad3bb912131270614820cf8ed59c9d94d4'}
2021-05-04 13:35:17,545 INFO    MainThread:58 [wandb_init.py:_log_setup():336] Logging user logs to /content/drive/My Drive/Trash/code/wandb/run-20210504_133517-1jm2ts80/logs/debug.log
2021-05-04 13:35:17,546 INFO    MainThread:58 [wandb_init.py:_log_setup():337] Logging internal logs to /content/drive/My Drive/Trash/code/wandb/run-20210504_133517-1jm2ts80/logs/debug-internal.log
2021-05-04 13:35:17,546 INFO    MainThread:58 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fab90a26e50>
2021-05-04 13:35:17,547 INFO    MainThread:58 [wandb_init.py:init():369] calling init triggers
2021-05-04 13:35:17,547 INFO    MainThread:58 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-04 13:35:17,547 INFO    MainThread:58 [wandb_init.py:init():418] starting backend
2021-05-04 13:35:17,547 INFO    MainThread:58 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-04 13:35:17,575 INFO    MainThread:58 [backend.py:ensure_launched():123] starting backend process...
2021-05-04 13:35:17,603 INFO    MainThread:58 [backend.py:ensure_launched():128] started backend process with pid: 381
2021-05-04 13:35:17,606 INFO    MainThread:58 [wandb_init.py:init():423] backend started and connected
2021-05-04 13:35:17,672 INFO    MainThread:58 [wandb_init.py:init():465] updated telemetry
2021-05-04 13:35:17,672 INFO    MainThread:58 [wandb_init.py:init():484] communicating current version
2021-05-04 13:35:18,428 INFO    MainThread:58 [wandb_init.py:init():489] got version response 
2021-05-04 13:35:18,428 INFO    MainThread:58 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-04 13:35:18,525 INFO    MainThread:58 [wandb_init.py:init():522] starting run threads in backend
2021-05-04 13:35:20,022 INFO    MainThread:58 [wandb_run.py:_console_start():1554] atexit reg
2021-05-04 13:35:20,026 INFO    MainThread:58 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-04 13:35:20,031 INFO    MainThread:58 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-04 13:35:20,031 INFO    MainThread:58 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-04 13:35:20,031 INFO    MainThread:58 [wandb_init.py:init():546] run started, returning control to user process
2021-05-04 13:35:20,031 INFO    MainThread:58 [wandb_config.py:__setitem__():141] config set learning_rate = 0.01 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fab8d6a2c10>>
2021-05-04 13:35:20,032 INFO    MainThread:58 [wandb_run.py:_config_callback():779] config_cb learning_rate 0.01 None
2021-05-04 13:35:20,032 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:20,033 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:35:20,048 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:35:25,204 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:25,205 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:35:25,212 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:35:37,284 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:37,284 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:35:38,525 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:35:38,551 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:38,551 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:35:38,557 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:35:38,582 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:38,582 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:35:39,672 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:35:39,681 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:39,681 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:35:39,691 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:35:39,695 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:39,696 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:35:39,707 INFO    MainThread:58 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:35:40,363 INFO    MainThread:58 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:35:40,365 INFO    MainThread:58 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:44:24,045 INFO    MainThread:58 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-04 13:44:24,046 INFO    MainThread:58 [wandb_run.py:_restore():1496] restore
2021-05-04 13:44:24,147 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 621
  total_bytes: 621
}

2021-05-04 13:44:24,821 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 621
  total_bytes: 7955
}

2021-05-04 13:44:24,924 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 621
  total_bytes: 7971
}

2021-05-04 13:44:25,027 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7971
  total_bytes: 7971
}

2021-05-04 13:44:25,130 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7971
  total_bytes: 7971
}

2021-05-04 13:44:25,233 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7971
  total_bytes: 7971
}

2021-05-04 13:44:25,335 INFO    MainThread:58 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7971
  total_bytes: 7971
}

2021-05-04 13:44:26,632 INFO    MainThread:58 [wandb_run.py:_show_files():1868] logging synced files
