2021-05-04 12:48:49,395 INFO    MainThread:1316 [wandb_setup.py:_flush():69] setting env: {}
2021-05-04 12:48:49,395 INFO    MainThread:1316 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-04 12:48:49,396 INFO    MainThread:1316 [wandb_init.py:_log_setup():336] Logging user logs to /content/drive/My Drive/Trash/code/wandb/run-20210504_124849-1n7umjip/logs/debug.log
2021-05-04 12:48:49,397 INFO    MainThread:1316 [wandb_init.py:_log_setup():337] Logging internal logs to /content/drive/My Drive/Trash/code/wandb/run-20210504_124849-1n7umjip/logs/debug-internal.log
2021-05-04 12:48:49,398 INFO    MainThread:1316 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd081583090>
2021-05-04 12:48:49,399 INFO    MainThread:1316 [wandb_init.py:init():369] calling init triggers
2021-05-04 12:48:49,399 INFO    MainThread:1316 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-04 12:48:49,399 INFO    MainThread:1316 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 18jgj601
2021-05-04 12:48:49,401 INFO    MainThread:1316 [wandb_run.py:finish():1197] finishing run pstage12/chanyub/18jgj601
2021-05-04 12:48:49,405 INFO    MainThread:1316 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-04 12:48:49,407 INFO    MainThread:1316 [wandb_run.py:_restore():1496] restore
2021-05-04 12:48:49,514 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 600
  total_bytes: 600
}

2021-05-04 12:48:49,846 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 600
  total_bytes: 8209
}

2021-05-04 12:48:50,011 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8209
  total_bytes: 8209
}

2021-05-04 12:48:50,114 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8209
  total_bytes: 8209
}

2021-05-04 12:48:50,216 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8209
  total_bytes: 8209
}

2021-05-04 12:48:50,318 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8209
  total_bytes: 8209
}

2021-05-04 12:48:50,421 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8209
  total_bytes: 8209
}

2021-05-04 12:48:51,752 INFO    MainThread:1316 [wandb_run.py:_show_files():1868] logging synced files
2021-05-04 12:48:51,766 INFO    MainThread:1316 [wandb_init.py:init():418] starting backend
2021-05-04 12:48:51,766 INFO    MainThread:1316 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-04 12:48:51,774 INFO    MainThread:1316 [backend.py:ensure_launched():123] starting backend process...
2021-05-04 12:48:51,834 INFO    MainThread:1316 [backend.py:ensure_launched():128] started backend process with pid: 1996
2021-05-04 12:48:51,836 INFO    MainThread:1316 [wandb_init.py:init():423] backend started and connected
2021-05-04 12:48:51,862 INFO    MainThread:1316 [wandb_init.py:init():465] updated telemetry
2021-05-04 12:48:51,879 INFO    MainThread:1316 [wandb_init.py:init():484] communicating current version
2021-05-04 12:48:52,722 INFO    MainThread:1316 [wandb_init.py:init():489] got version response 
2021-05-04 12:48:52,722 INFO    MainThread:1316 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-04 12:48:52,826 INFO    MainThread:1316 [wandb_init.py:init():522] starting run threads in backend
2021-05-04 12:48:54,497 INFO    MainThread:1316 [wandb_run.py:_console_start():1554] atexit reg
2021-05-04 12:48:54,503 INFO    MainThread:1316 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-04 12:48:54,504 INFO    MainThread:1316 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-04 12:48:54,504 INFO    MainThread:1316 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-04 12:48:54,504 INFO    MainThread:1316 [wandb_init.py:init():546] run started, returning control to user process
2021-05-04 12:48:54,506 INFO    MainThread:1316 [wandb_config.py:__setitem__():141] config set learning_rate = 0.01 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fd081583390>>
2021-05-04 12:48:54,507 INFO    MainThread:1316 [wandb_run.py:_config_callback():779] config_cb learning_rate 0.01 None
2021-05-04 12:48:54,507 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 12:48:54,508 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 12:48:54,520 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 12:48:57,104 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 12:48:57,104 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 12:48:57,111 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 12:49:00,647 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 12:49:00,648 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 12:49:00,656 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 12:49:00,681 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 12:49:00,682 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 12:49:00,693 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 12:49:00,718 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 12:49:00,719 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 12:49:00,729 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 12:49:00,735 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 12:49:00,735 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 12:49:00,741 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 12:49:00,746 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 12:49:00,746 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 12:49:00,759 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:24:24,460 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:24:24,461 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:24:25,823 INFO    MainThread:1316 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-04 13:27:53,975 INFO    MainThread:1316 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-04 13:27:53,975 INFO    MainThread:1316 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-04 13:29:26,134 INFO    MainThread:1316 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-04 13:29:26,135 INFO    MainThread:1316 [wandb_run.py:_restore():1496] restore
2021-05-04 13:29:26,233 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 600
  total_bytes: 600
}

2021-05-04 13:29:27,201 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 600
  total_bytes: 8284
}

2021-05-04 13:29:27,305 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 923
  total_bytes: 8284
}

2021-05-04 13:29:27,409 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8284
  total_bytes: 8284
}

2021-05-04 13:29:27,512 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8284
  total_bytes: 8284
}

2021-05-04 13:29:27,614 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8284
  total_bytes: 8284
}

2021-05-04 13:29:27,716 INFO    MainThread:1316 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8284
  total_bytes: 8284
}

2021-05-04 13:29:29,044 INFO    MainThread:1316 [wandb_run.py:_show_summary():1801] rendering summary
2021-05-04 13:29:29,046 INFO    MainThread:1316 [wandb_run.py:_show_history():1839] rendering history
2021-05-04 13:29:29,048 INFO    MainThread:1316 [wandb_run.py:_show_files():1868] logging synced files
